package com.nuclear.boomm.product.enums;

public enum CoverageCategory {

    MANDATORY_BASIC_COVERAGE,
    LIABILITY_LIMITS_FOR_BODILY_INJURY,
    PROPERTY_DAMAGE,
    SELF_BODILY_INJURY_COVERAGE,
    OWN_DAMAGE_COVERAGE,
    CORE_DIFFERENTIATION_RIDERS,
    AGE_AND_DRIVER_SCOPE_RIDERS,
    OTHER_ESSENTIAL_RIDERS
}
