package com.nuclear.boomm.product.enums;

public enum FeedbackStatus {

    STAKEHOLDER_FEEDBACK_PENDING,
    APPROVAL,
    COMPLIANCE_FEEDBACK_PENDING,
    COMPLIANCE_FEEDBACK_UPDATE,
    STAKEHOLDER_FEEDBACK_UPDATE,
    ADDITIONAL_EXPLANATION_REQUEST,
    RISK_REPORT_FEEDBACK_PENDING,
    RISK_REPORT_FEEDBACK_UPDATE,
    STAKEHOLDER_FEEDBACK_UPDATE_PENDING,
    ADDITIONAL_EXPLANATION_UPDATE_PENDING,
    COMPLIANCE_FEEDBACK_UPDATE_PENDING,
    RELEASE_APPROVAL,
    RISK_REPORT_FEEDBACK_UPDATE_PENDING
}
