package com.nuclear.boomm.product.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum FeedbackStatus {

    STAKEHOLDER_FEEDBACK_PENDING("STAKEHOLDER_FEEDBACK_PENDING", "이해관계자의 피드백 대기중"),
    APPROVAL("APPROVAL", "컴플라이언스 팀으로 이관 승인"),
    COMPLIANCE_FEEDBACK_PENDING("COMPLIANCE_FEEDBACK_PENDING", "컴플라이언스의 피드백 대기중"),
    COMPLIANCE_FEEDBACK_UPDATE("COMPLIANCE_FEEDBACK_UPDATE", "컴플라이언스의 피드백 반영됨"),
    STAKEHOLDER_FEEDBACK_UPDATE("STAKEHOLDER_FEEDBACK_UPDATE", "이해관계자의 피드백 반영됨"),
    ADDITIONAL_EXPLANATION_REQUEST("ADDITIONAL_EXPLANATION_REQUEST", "추가 설명 요청"),
    RISK_REPORT_FEEDBACK_PENDING("RISK_REPORT_FEEDBACK_PENDING", "위험보고서 피드백 대기중"),
    RISK_REPORT_FEEDBACK_UPDATE("RISK_REPORT_FEEDBACK_UPDATE", "위험보고서 피드백 반영됨"),
    STAKEHOLDER_FEEDBACK_UPDATE_PENDING("STAKEHOLDER_FEEDBACK_UPDATE_PENDING", "이해관계자 피드백 반영 대기중"),
    ADDITIONAL_EXPLANATION_UPDATE_PENDING("ADDITIONAL_EXPLANATION_UPDATE_PENDING", "추가 설명 반영 대기중"),
    COMPLIANCE_FEEDBACK_UPDATE_PENDING("COMPLIANCE_FEEDBACK_UPDATE_PENDING", "컴플라이언스의 피드백 반영 대기중"),
    RELEASE_APPROVAL("RELEASE_APPROVAL", "상품 출시 승인"),
    RISK_REPORT_FEEDBACK_UPDATE_PENDING("RISK_REPORT_FEEDBACK_UPDATE_PENDING", "위험보고서 피드백 반영 대기중");

    private final String key;
    private final String title;
}
